#!/usr/bin/env python3
"""bob analyze — retrofit scaffolder for existing/brownfield projects.

Scans a codebase and generates a DRAFT constitution + DRAFT spec stubs so a messy
project can be brought into the BOB spec layer without writing everything by hand.
It does NOT invent rationale — every generated file is marked status: draft with
TODO markers for a human (or the BOB workflow's expensive model) to fill in the
intent and contract. Pair this with references/retrofit-existing.md and
characterization tests before changing any behavior.

Usage:
    python bob_analyze.py [PROJECT_ROOT] [--write]

Without --write it prints what it would create (dry run). With --write it creates
constitution.md (if absent) and specs/_drafts/ stubs for detected components.

Dependency-free; stdlib only.
"""
from __future__ import annotations

import argparse
from pathlib import Path

SOURCE_EXT = {".py", ".js", ".ts", ".tsx", ".jsx", ".go", ".rs", ".java", ".rb", ".sql"}
SKIP_DIRS = {".git", "node_modules", "__pycache__", ".venv", "venv", "dist", "build", ".github"}

CONSTITUTION_STUB = """# Project Constitution — {name} (DRAFT — retrofit)

Version: 0.1 · Last updated: TODO · Owner: TODO

Generated by `bob analyze`. Fill in the TODOs from the conventions already in the
code, then converge the inconsistencies it can't decide. Get sign-off before relying
on it.

## 1. Technology standards
- Detected languages: {languages}
- TODO: pin runtimes, frameworks, allowed/forbidden deps.

## 2. Naming conventions
- TODO: capture the conventions actually in use; name the inconsistencies to fix.

## 3. Architecture rules & boundaries
- Detected top-level modules: {modules}
- TODO: state allowed dependency directions and boundaries.

## 4. Governance
- TODO: spec approval, versioning, breaking-change policy.

## 5. Invariants (must hold platform-wide)
- TODO.

## 6. Amendment log
- TODO — created via bob analyze (retrofit).
"""

SPEC_STUB = """---
id: {sid}
type: {stype}
version: 0.1
status: draft
owner: TODO
depends_on: []
consumed_by: []
---

## Intent
TODO — WHY does `{component}` exist? Recover the rationale; mark unknowns as open
questions instead of inventing them.

## Contract
TODO — describe what `{component}` actually does today (from the code), then the
intended contract.

## Business rules
TODO — assumptions, constraints, edge cases observed in the code.

## Downstream impact
TODO — what depends on this; what breaks if it changes.

## Verification
TODO — add a characterization test that pins current behavior before any change.
"""


def scan(root: Path):
    languages = set()
    modules = set()
    components = []
    for p in root.rglob("*"):
        if any(part in SKIP_DIRS for part in p.parts):
            continue
        if p.is_file() and p.suffix in SOURCE_EXT:
            languages.add(p.suffix.lstrip("."))
            rel = p.relative_to(root)
            if len(rel.parts) > 1:
                modules.add(rel.parts[0])
            components.append(rel.as_posix())
    return sorted(languages), sorted(modules), components


def main(argv=None):
    ap = argparse.ArgumentParser(description="Scaffold a BOB spec layer from existing code.")
    ap.add_argument("root", nargs="?", default=".")
    ap.add_argument("--write", action="store_true", help="actually create files")
    args = ap.parse_args(argv)

    root = Path(args.root).resolve()
    languages, modules, components = scan(root)

    print(f"Scanned {root}")
    print(f"  languages: {', '.join(languages) or 'none detected'}")
    print(f"  top-level modules: {', '.join(modules) or 'none'}")
    print(f"  source files: {len(components)}")

    plan = []
    if not (root / "constitution.md").exists():
        plan.append("constitution.md (draft)")
    # one draft spec stub per top-level module, typed 'transformation' as a starting guess.
    for m in modules or ["core"]:
        plan.append(f"specs/_drafts/transformation-{m}.md (draft)")

    print("\nWould create:" if not args.write else "\nCreating:")
    for item in plan:
        print(f"  + {item}")

    if not args.write:
        print("\n(dry run — re-run with --write to create these draft files)")
        return 0

    name = root.name
    cpath = root / "constitution.md"
    if not cpath.exists():
        cpath.write_text(
            CONSTITUTION_STUB.format(
                name=name,
                languages=", ".join(languages) or "TODO",
                modules=", ".join(modules) or "TODO",
            ),
            encoding="utf-8",
        )
    draft_dir = root / "specs" / "_drafts"
    draft_dir.mkdir(parents=True, exist_ok=True)
    for m in modules or ["core"]:
        sid = f"transformation-{m}"
        (draft_dir / f"{sid}.md").write_text(
            SPEC_STUB.format(sid=sid, stype="transformation", component=m),
            encoding="utf-8",
        )
    print("\nDone. Now: fill the TODOs, add characterization tests, set status to "
          "approved, then run scripts/bob_validate.py .")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
